FlowRouter.route("/", {
	name:"mainLayout",
	action(){
		BlazeLayout.render("mainLayout");
	}
});
FlowRouter.route("/carrera",{
	name:"carrera",
	action(){
		BlazeLayout.render("mainLayout",{main:"carrera"});
	}
});
FlowRouter.route("/facultad",{
	name:"facultad",
	action(){
		BlazeLayout.render("mainLayout",{main:"facultad"});
	}
});
FlowRouter.route("/User",{
	name:"User",
	action(){
		BlazeLayout.render("mainLayout",{main:"User"});
	}
});
FlowRouter.route("/UnidadM",{
	name:"UnidadM",
	action(){
		BlazeLayout.render("mainLayout",{main:"UnidadM"});
	}
});
FlowRouter.route("/UnidadD",{
	name:"UnidadD",
	action(){
		BlazeLayout.render("mainLayout",{main:"UnidadD"});
	}
});
FlowRouter.route("/dig",{
	name:"dig",
	action(){
		BlazeLayout.render("mainLayout",{main:"dig"});
	}
});
FlowRouter.route("/fordig",{
	name:"fordig",
	action(){
		BlazeLayout.render("mainLayout",{main:"fordig"});
	}
});
FlowRouter.route("/upload",{
	name:"upload",
	action(){
		BlazeLayout.render("mainLayout",{main:"uploadForm"});
	}
});